---
permalink: api/reference_element_api_rekeysoftwareencryptionatrestmasterkey.html 
sidebar: sidebar 
keywords: system, api, element, security, rekey, software encryption at rest 
summary: 您可以使用 RekeySoftwareEncryptionAtRestMasterKey 方法重新设置用于加密磁盘（数据加密密钥）的软件空闲加密主密钥的密钥。 
---
= RekeySoftwareEncryptionAtRestMasterKey
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `RekeySoftwareEncryptionAtRestMasterKey`方法重新设置用于加密DEks (数据加密密钥)的软件空闲加密主密钥的密钥。在创建集群期间，系统会将空闲软件加密配置为使用内部密钥管理（ InInternal Key Management ， KKM ）。创建集群后，可以使用此重新设置密钥方法来使用 IKM 或外部密钥管理（ External Key Management ， EKM ）。



== 参数

此方法具有以下输入参数。如果 `keyManagementType`未指定参数、则会使用现有密钥管理配置执行重新设置密钥操作。如果 `keyManagementType`指定了且密钥提供程序为外部、则 `keyProviderID`还必须使用参数。

[cols="4*"]
|===
| 参数 | 说明 | 键入 | 可选 


| KeyManagementType | 用于管理主密钥的密钥管理类型。可能值包括
`Internal`：：使用内部密钥管理重新设置密钥。
`External`：使用外部密钥管理重新设置密钥。如果未指定此参数，则使用现有密钥管理配置执行重新设置密钥操作。 | string | 正确 


| 密钥提供程序 ID | 要使用的密钥提供程序的 ID 。这是作为其中一个方法的一部分返回的唯一值 `CreateKeyProvider`。只有当为 `External`和无效时、才需要此ID `keyManagementType`。 | 整型 | 正确 
|===


== 返回值

此方法具有以下返回值：

[cols="4*"]
|===
| 参数 | 说明 | 键入 | 可选 


| 异步处理 | 使用此值和 `GetAsyncResult`确定重新设置密钥操作的状态 `asyncHandle`。 `GetAsyncResult`输出将包括一个 `newKey`字段、其中包含有关新主密钥的信息、以及一个字段、 `keyToDecommission`其中包含有关旧密钥的信息。 | 整型 | 错 
|===


== 请求示例

此方法的请求类似于以下示例：

[listing]
----
{
 "method": "rekeysoftwareencryptionatrestmasterkey",
 "params": {
   "keyManagementType": "external",
   "keyProviderID": "<ID number>"
 }
}
----


== 响应示例

此方法返回类似于以下示例的响应：

[listing]
----
{
    "asyncHandle": 1
}
----


== 自版本以来的新增功能

12.3

[discrete]
== 了解更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 和 Element 软件文档"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["早期版本的 NetApp SolidFire 和 Element 产品的文档"^]

